import BuscaMarcasInput from '../components/BuscaMarcasInput'
import BuscaVoltagemInput from '../components/BuscaVoltagemInput'



export const TIPOS_ORDEM = [
  { value: '1', label: 'Motor C.A' },
  { value: '2', label: 'Motor C.C' },
  { value: '3', label: 'Motor E.X' },
  { value: '4', label: 'Motor Síncrono' },
  { value: '5', label: 'Motor Monofásico' },
  { value: '6', label: 'Transformador' },
  { value: '7', label: 'Servo Motor' },
  { value: '8', label: 'Drives' },
  { value: '9', label: 'Campo M.C.A' },
  { value: '10', label: 'Campo Transformador' },
  { value: '11', label: 'Campo Geral' },
  { value: '12', label: 'Motor Bomba' },
  { value: '13', label: 'Bomba' },
  { value: '14', label: 'Redutor' },
  { value: '15', label: 'Gerador' },
  { value: '16', label: 'Eixo' },
  { value: '17', label: 'Carcaça' },
]

export const ORDER_FIELDS_CONFIG = {
  1: {
    // Motor C.A
    nome: 'Motor C.A',
    campos: [
      { key: 'orde_pote', label: 'Potência', tipo: 'text', required: true },
      { key: 'orde_volt', label: 'Tensão', tipo: 'BuscaVoltagemInput', required: true },
      { key: 'orde_ampe', label: 'Corrente', tipo: 'text', required: true },
      { key: 'orde_hz', label: 'Frequência', tipo: 'text', required: true },
      { key: 'orde_rpm', label: 'Rotação', tipo: 'text', required: true },
      {
        key: 'orde_marc',
        label: 'Marca',
        tipo: 'BuscaMarcasInput',
        required: true,
      },
      { key: 'orde_seri', label: 'N° de série', tipo: 'text', required: false },
      { key: 'orde_mode', label: 'Modelo', tipo: 'text', required: false },
      { key: 'orde_patr', label: 'TAG', tipo: 'text', required: false },
      {
        key: 'orde_foco',
        label: 'Forma Construtiva',
        tipo: 'text',
        required: false,
      },
      {
        key: 'orde_esta_cabo',
        label: 'Cabos Caixa de Ligação',
        tipo: 'text',
        required: false,
      },
      {
        key: 'orde_esta_liga',
        label: 'Status Caixa de Ligação',
        tipo: 'text',
        required: false,
      },
      {
        key: 'orde_grau_ip',
        label: 'Grau de IP',
        tipo: 'text',
        required: false,
      },
      {
        key: 'orde_isol',
        label: 'Isolamento',
        tipo: 'text',
        required: false,
      },
      {
        key: 'orde_obse',
        label: 'Observações',
        tipo: 'textarea',
        required: false,
      },
    ],
  },
  2: {
    // Motor C.C
    nome: 'Motor C.C',
    campos: [
      { key: 'orde_pote', label: 'Potência', tipo: 'text', required: true },

      {
        key: 'orde_tens_camp',
        label: 'Tensão de Campo',
        tipo: 'text',
        required: true,
      },
      {
        key: 'orde_corr_camp',
        label: 'Corrente de Campo',
        tipo: 'text',
        required: true,
      },
      {
        key: 'orde_tens_arma',
        label: 'Tensão de Armadura',
        tipo: 'text',
        required: true,
      },
      {
        key: 'orde_corr_arma',
        label: 'Corrente da Armadura',
        tipo: 'text',
        required: true,
      },
      {
        key: 'orde_rpm',
        label: 'Range de Rotação',
        tipo: 'text',
        required: true,
      },
      {
        key: 'orde_marc',
        label: 'Marca',
        tipo: 'BuscaMarcasInput',
        required: true,
      },
      { key: 'orde_seri', label: 'N° de série', tipo: 'text', required: false },
      { key: 'orde_mode', label: 'Modelo', tipo: 'text', required: false },
      { key: 'orde_patr', label: 'TAG', tipo: 'text', required: false },
      {
        key: 'orde_foco',
        label: 'Forma Construtiva',
        tipo: 'text',
        required: false,
      },
      {
        key: 'orde_esta_cabo',
        label: 'Cabos Caixa de Ligação',
        tipo: 'text',
        required: false,
      },
      {
        key: 'orde_esta_liga',
        label: 'Status Caixa de Ligação',
        tipo: 'text',
        required: false,
      },
      {
        key: 'orde_grau_ip',
        label: 'Grau de IP',
        tipo: 'text',
        required: false,
      },
      {
        key: 'orde_isol',
        label: 'Isolamento',
        tipo: 'text',
        required: false,
      },
      {
        key: 'orde_obse',
        label: 'Observações',
        tipo: 'textarea',
        required: false,
      },
    ],
  },
  3: {
    // Motor E.X
    nome: 'Motor E.X',
    campos: [
      { key: 'orde_pote', label: 'Potência', tipo: 'text', required: true },
      { key: 'orde_volt', label: 'Tensão', tipo: 'text', required: true },
      { key: 'orde_ampe', label: 'Corrente', tipo: 'text', required: true },
      { key: 'orde_hz', label: 'Frequência', tipo: 'text', required: true },
      { key: 'orde_rpm', label: 'Rotação', tipo: 'text', required: true },
      {
        key: 'orde_marc',
        label: 'Marca',
        tipo: 'BuscaMarcasInput',
        required: true,
      },
      { key: 'orde_seri', label: 'N° de série', tipo: 'text', required: false },
      { key: 'orde_mode', label: 'Modelo', tipo: 'text', required: false },
      { key: 'orde_patr', label: 'TAG', tipo: 'text', required: false },
      {
        key: 'orde_foco',
        label: 'Forma Construtiva',
        tipo: 'text',
        required: false,
      },
      {
        key: 'orde_esta_cabo',
        label: 'Cabos Caixa de Ligação',
        tipo: 'text',
        required: false,
      },
      {
        key: 'orde_esta_liga',
        label: 'Status Caixa de Ligação',
        tipo: 'text',
        required: false,
      },
      {
        key: 'orde_grau_ip',
        label: 'Grau de IP',
        tipo: 'text',
        required: false,
      },
      {
        key: 'orde_isol',
        label: 'Isolamento',
        tipo: 'text',
        required: false,
      },
      {
        key: 'orde_obse',
        label: 'Observações',
        tipo: 'textarea',
        required: false,
      },
    ],
  },
  4: {
    // Motor Síncrono
    nome: 'Motor Síncrono',
    campos: [
      { key: 'orde_pote', label: 'Potência', tipo: 'text', required: true },
      {
        key: 'orde_volt',
        label: 'Tensão do primário',
        tipo: 'BuscaVoltagemInput',
        required: true,
      },
      {
        key: 'orde_ampe',
        label: 'Corrente do primário',
        tipo: 'text',
        required: true,
      },
      {
        key: 'orde_marc',
        label: 'Marca',
        tipo: 'BuscaMarcasInput',
        required: true,
      },
      { key: 'orde_seri', label: 'N° de série', tipo: 'text', required: false },
      { key: 'orde_mode', label: 'Modelo', tipo: 'text', required: false },
      { key: 'orde_patr', label: 'TAG', tipo: 'text', required: false },
      {
        key: 'orde_foco',
        label: 'Forma Construtiva',
        tipo: 'text',
        required: false,
      },
      {
        key: 'orde_esta_cabo',
        label: 'Cabos Caixa de Ligação',
        tipo: 'text',
        required: false,
      },
      {
        key: 'orde_esta_liga',
        label: 'Status Caixa de Ligação',
        tipo: 'text',
        required: false,
      },
      {
        key: 'orde_grau_ip',
        label: 'Grau de IP',
        tipo: 'text',
        required: false,
      },
      {
        key: 'orde_isol',
        label: 'Isolamento',
        tipo: 'text',
        required: false,
      },
      {
        key: 'orde_obse',
        label: 'Observações',
        tipo: 'textarea',
        required: false,
      },
    ],
  },
  5: {
    // Motor Monofásico
    nome: 'Motor Monofásico',
    campos: [
      { key: 'orde_pote', label: 'Potência', tipo: 'text', required: true },
      {
        key: 'orde_volt',
        label: 'Tensão',
        tipo: 'BuscaVoltagemInput',
        required: true,
      },
      { key: 'orde_ampe', label: 'Corrente', tipo: 'text', required: true },
      { key: 'orde_hz', label: 'Frequência', tipo: 'text', required: true },
      { key: 'orde_rpm', label: 'Rotação', tipo: 'text', required: true },
      {
        key: 'orde_marc',
        label: 'Marca',
        tipo: 'BuscaMarcasInput',
        required: true,
      },
      { key: 'orde_seri', label: 'N° de série', tipo: 'text', required: false },
      { key: 'orde_mode', label: 'Modelo', tipo: 'text', required: false },
      { key: 'orde_patr', label: 'TAG', tipo: 'text', required: false },
      {
        key: 'orde_foco',
        label: 'Forma Construtiva',
        tipo: 'text',
        required: false,
      },
      {
        key: 'orde_esta_cabo',
        label: 'Cabos Caixa de Ligação',
        tipo: 'text',
        required: false,
      },
      {
        key: 'orde_esta_liga',
        label: 'Status Caixa de Ligação',
        tipo: 'text',
        required: false,
      },
      {
        key: 'orde_grau_ip',
        label: 'Grau de IP',
        tipo: 'text',
        required: false,
      },
      {
        key: 'orde_isol',
        label: 'Isolamento',
        tipo: 'text',
        required: false,
      },
      {
        key: 'orde_obse',
        label: 'Observações',
        tipo: 'textarea',
        required: false,
      },
    ],
  },
  6: {
    // Transformador
    nome: 'Transformador',
    campos: [
      { key: 'orde_pote', label: 'Potência', tipo: 'text', required: true },
      {
        key: 'orde_volt',
        label: 'Tensão Primário',
        tipo: 'BuscaVoltagemInput',
        required: true,
      },
      {
        key: 'orde_ampe',
        label: 'Corrente Primário',
        tipo: 'text',
        required: true,
      },
      { key: 'orde_hz', label: 'Frequência', tipo: 'text', required: true },
      {
        key: 'orde_marc',
        label: 'Marca',
        tipo: 'BuscaMarcasInput',
        required: true,
      },
      { key: 'orde_seri', label: 'N° de série', tipo: 'text', required: false },
      { key: 'orde_mode', label: 'Modelo', tipo: 'text', required: false },
      { key: 'orde_patr', label: 'TAG', tipo: 'text', required: false },
      {
        key: 'orde_esta_liga',
        label: 'Ligação',
        tipo: 'text',
        required: false,
      },
      {
        key: 'orde_obse',
        label: 'Observações',
        tipo: 'textarea',
        required: false,
      },
    ],
  },
  7: {
    // Servo Motor
    nome: 'Servo Motor',
    campos: [
      { key: 'orde_pote', label: 'Potência', tipo: 'text', required: true },
      {
        key: 'orde_volt',
        label: 'Tensão',
        tipo: 'BuscaVoltagemInput',
        required: true,
      },
      { key: 'orde_ampe', label: 'Corrente', tipo: 'text', required: true },
      { key: 'orde_rpm', label: 'Rotação', tipo: 'text', required: true },
      {
        key: 'orde_marc',
        label: 'Marca',
        tipo: 'BuscaMarcasInput',
        required: true,
      },
      { key: 'orde_seri', label: 'N° de série', tipo: 'text', required: false },
      { key: 'orde_mode', label: 'Modelo', tipo: 'text', required: false },
      { key: 'orde_patr', label: 'TAG', tipo: 'text', required: false },
      {
        key: 'orde_grau_ip',
        label: 'Grau de IP',
        tipo: 'text',
        required: false,
      },
      {
        key: 'orde_isol',
        label: 'Isolamento',
        tipo: 'text',
        required: false,
      },
      {
        key: 'orde_obse',
        label: 'Observações',
        tipo: 'textarea',
        required: false,
      },
    ],
  },
  8: {
    // Drives
    nome: 'Drives',
    campos: [
      { key: 'orde_pote', label: 'Potência', tipo: 'text', required: true },
      {
        key: 'orde_volt',
        label: 'Tensão',
        tipo: 'BuscaVoltagemInput',
        required: true,
      },
      { key: 'orde_ampe', label: 'Corrente', tipo: 'text', required: true },
      { key: 'orde_hz', label: 'Frequência', tipo: 'text', required: true },
      {
        key: 'orde_marc',
        label: 'Marca',
        tipo: 'BuscaMarcasInput',
        required: true,
      },
      { key: 'orde_seri', label: 'N° de série', tipo: 'text', required: false },
      { key: 'orde_mode', label: 'Modelo', tipo: 'text', required: false },
      { key: 'orde_patr', label: 'TAG', tipo: 'text', required: false },
      {
        key: 'orde_obse',
        label: 'Observações',
        tipo: 'textarea',
        required: false,
      },
    ],
  },
  9: {
    // Campo M.C.A
    nome: 'Campo M.C.A',
    campos: [
      { key: 'orde_pote', label: 'Potência', tipo: 'text', required: true },
      {
        key: 'orde_volt',
        label: 'Tensão',
        tipo: 'BuscaVoltagemInput',
        required: true,
      },
      { key: 'orde_ampe', label: 'Corrente', tipo: 'text', required: true },
      { key: 'orde_hz', label: 'Frequência', tipo: 'text', required: true },
      { key: 'orde_rpm', label: 'Rotação', tipo: 'text', required: true },
      {
        key: 'orde_marc',
        label: 'Marca',
        tipo: 'BuscaMarcasInput',
        required: true,
      },
      { key: 'orde_seri', label: 'N° de série', tipo: 'text', required: false },
      { key: 'orde_mode', label: 'Modelo', tipo: 'text', required: false },
      {
        key: 'orde_grau_ip',
        label: 'Grau de IP',
        tipo: 'text',
        required: false,
      },
      {
        key: 'orde_isol',
        label: 'Isolamento',
        tipo: 'text',
        required: false,
      },
    ],
  },
  10: {
    // Campo Transformador
    nome: 'Campo Transformador',
    campos: [
      { key: 'orde_pote', label: 'Potência', tipo: 'text', required: true },
      {
        key: 'orde_volt',
        label: 'Tensão Primário',
        tipo: 'BuscaVoltagemInput',
        required: true,
      },
      {
        key: 'orde_ampe',
        label: 'Corrente Primário',
        tipo: 'text',
        required: true,
      },
      { key: 'orde_hz', label: 'Frequência', tipo: 'text', required: true },
      {
        key: 'orde_marc',
        label: 'Marca',
        tipo: 'BuscaMarcasInput',
        required: true,
      },
      { key: 'orde_seri', label: 'N° de série', tipo: 'text', required: false },
      { key: 'orde_mode', label: 'Modelo', tipo: 'text', required: false },
      { key: 'orde_patr', label: 'TAG', tipo: 'text', required: false },
      {
        key: 'orde_esta_liga',
        label: 'Ligação',
        tipo: 'text',
        required: false,
      },
      {
        key: 'orde_grau_ip',
        label: 'Grau de IP',
        tipo: 'text',
        required: false,
      },
      {
        key: 'orde_isol',
        label: 'Isolamento',
        tipo: 'text',
        required: false,
      },
      {
        key: 'orde_obse',
        label: 'Observações',
        tipo: 'textarea',
        required: false,
      },
    ],
  },
  11: {
    // Campo Geral
    nome: 'Campo Geral',
    campos: [
      { key: 'orde_pote', label: 'Potência', tipo: 'text', required: true },
      {
        key: 'orde_volt',
        label: 'Tensão',
        tipo: 'BuscaVoltagemInput',
        required: true,
      },
      { key: 'orde_ampe', label: 'Corrente', tipo: 'text', required: true },
      { key: 'orde_hz', label: 'Frequência', tipo: 'text', required: true },
      { key: 'orde_rpm', label: 'Rotação', tipo: 'text', required: true },
      {
        key: 'orde_marc',
        label: 'Marca',
        tipo: 'BuscaMarcasInput',
        required: true,
      },
      { key: 'orde_seri', label: 'N° de série', tipo: 'text', required: false },
      { key: 'orde_mode', label: 'Modelo', tipo: 'text', required: false },
      { key: 'orde_patr', label: 'TAG', tipo: 'text', required: false },
      {
        key: 'orde_foco',
        label: 'Forma Construtiva',
        tipo: 'text',
        required: false,
      },
      {
        key: 'orde_obse',
        label: 'Observações',
        tipo: 'textarea',
        required: false,
      },
    ],
  },
  12: {
    // Motor Bomba
    nome: 'Motor Bomba',
    campos: [
      { key: 'orde_pote', label: 'Potência', tipo: 'text', required: true },
      {
        key: 'orde_volt',
        label: 'Tensão',
        tipo: 'BuscaVoltagemInput',
        required: true,
      },
      { key: 'orde_ampe', label: 'Corrente', tipo: 'text', required: true },
      { key: 'orde_hz', label: 'Frequência', tipo: 'text', required: true },
      { key: 'orde_rpm', label: 'Rotação', tipo: 'text', required: true },
      {
        key: 'orde_marc',
        label: 'Marca Motor',
        tipo: 'BuscaMarcasInput',
        required: true,
      },
      {
        key: 'orde_seri',
        label: 'N° de série Motor',
        tipo: 'text',
        required: false,
      },
      { key: 'orde_mode', label: 'Modelo', tipo: 'text', required: false },
      { key: 'orde_patr', label: 'TAG', tipo: 'text', required: false },
      {
        key: 'orde_foco',
        label: 'Forma Construtiva',
        tipo: 'text',
        required: false,
      },
      {
        key: 'orde_esta_cabo',
        label: 'Cabos Caixa de Ligação',
        tipo: 'text',
        required: false,
      },
      {
        key: 'orde_esta_liga',
        label: 'Status Caixa de Ligação',
        tipo: 'text',
        required: false,
      },
      {
        key: 'orde_grau_ip',
        label: 'Grau de IP',
        tipo: 'text',
        required: false,
      },
      {
        key: 'orde_isol',
        label: 'Isolamento',
        tipo: 'text',
        required: false,
      },
      {
        key: 'orde_obse',
        label: 'Observações',
        tipo: 'textarea',
        required: false,
      },
    ],
  },
  13: {
    // Bomba
    nome: 'Bomba',
    campos: [
      { key: 'orde_pote', label: 'Potência', tipo: 'text', required: true },
      { key: 'orde_rpm', label: 'Rotação', tipo: 'text', required: true },
      {
        key: 'orde_marc',
        label: 'Marca',
        tipo: 'BuscaMarcasInput',
        required: true,
      },
      { key: 'orde_seri', label: 'N° de série', tipo: 'text', required: false },
      { key: 'orde_mode', label: 'Modelo', tipo: 'text', required: false },
      { key: 'orde_patr', label: 'TAG', tipo: 'text', required: false },
      {
        key: 'orde_obse',
        label: 'Observações',
        tipo: 'textarea',
        required: false,
      },
    ],
  },
  14: {
    // Redutor
    nome: 'Redutor',
    campos: [
      { key: 'orde_pote', label: 'Potência', tipo: 'text', required: true },
      {
        key: 'orde_rpm',
        label: 'Rotação eixo de entrada',
        tipo: 'text',
        required: true,
      },
      {
        key: 'orde_marc',
        label: 'Marca',
        tipo: 'BuscaMarcasInput',
        required: true,
      },
      { key: 'orde_seri', label: 'N° de série', tipo: 'text', required: false },
      { key: 'orde_mode', label: 'Modelo', tipo: 'text', required: false },
      { key: 'orde_patr', label: 'TAG', tipo: 'text', required: false },
      {
        key: 'orde_obse',
        label: 'Observações',
        tipo: 'textarea',
        required: false,
      },
    ],
  },
  15: {
    // Gerador
    nome: 'Gerador',
    campos: [
      { key: 'orde_pote', label: 'Potência', tipo: 'text', required: true },
      {
        key: 'orde_volt',
        label: 'Tensão',
        tipo: 'BuscaVoltagemInput',
        required: true,
      },
      { key: 'orde_ampe', label: 'Corrente', tipo: 'text', required: true },
      { key: 'orde_hz', label: 'Frequência', tipo: 'text', required: true },
      { key: 'orde_rpm', label: 'Rotação', tipo: 'text', required: true },
      {
        key: 'orde_marc',
        label: 'Marca',
        tipo: 'BuscaMarcasInput',
        required: true,
      },
      { key: 'orde_seri', label: 'N° de série', tipo: 'text', required: false },
      { key: 'orde_mode', label: 'Modelo', tipo: 'text', required: false },
      { key: 'orde_patr', label: 'TAG', tipo: 'text', required: false },
      {
        key: 'orde_foco',
        label: 'Forma Construtiva',
        tipo: 'text',
        required: false,
      },
      {
        key: 'orde_esta_cabo',
        label: 'Cabos Caixa de Ligação',
        tipo: 'text',
        required: false,
      },
      {
        key: 'orde_esta_liga',
        label: 'Status Caixa de Ligação',
        tipo: 'text',
        required: false,
      },
      {
        key: 'orde_grau_ip',
        label: 'Grau de IP',
        tipo: 'text',
        required: false,
      },
      {
        key: 'orde_isol',
        label: 'Isolamento',
        tipo: 'text',
        required: false,
      },
      {
        key: 'orde_obse',
        label: 'Observações',
        tipo: 'textarea',
        required: false,
      },
    ],
  },
  16: {
    // Eixo
    nome: 'Eixo',
    campos: [
      {
        key: 'orde_obse',
        label: 'Observações',
        tipo: 'textarea',
        required: false,
      },
    ],
  },
  17: {
    // Carcaça
    nome: 'Carcaça',
    campos: [
      { key: 'orde_pote', label: 'Potência', tipo: 'text', required: true },
      {
        key: 'orde_volt',
        label: 'Tensão',
        tipo: 'BuscaVoltagemInput',
        required: true,
      },
      { key: 'orde_ampe', label: 'Corrente', tipo: 'text', required: true },
      { key: 'orde_hz', label: 'Frequência', tipo: 'text', required: true },
      { key: 'orde_rpm', label: 'Rotação', tipo: 'text', required: true },
      {
        key: 'orde_marc',
        label: 'Marca',
        tipo: 'BuscaMarcasInput',
        required: true,
      },
      { key: 'orde_seri', label: 'N° de série', tipo: 'text', required: false },
      { key: 'orde_mode', label: 'Modelo', tipo: 'text', required: false },
      { key: 'orde_patr', label: 'TAG', tipo: 'text', required: false },
      {
        key: 'orde_esta_cabo',
        label: 'Cabos Caixa de Ligação',
        tipo: 'text',
        required: false,
      },
      {
        key: 'orde_esta_liga',
        label: 'Status Caixa de Ligação',
        tipo: 'text',
        required: false,
      },
      {
        key: 'orde_grau_ip',
        label: 'Grau de IP',
        tipo: 'text',
        required: false,
      },
      {
        key: 'orde_isol',
        label: 'Isolamento',
        tipo: 'text',
        required: false,
      },
      {
        key: 'orde_obse',
        label: 'Observações',
        tipo: 'textarea',
        required: false,
      },
    ],
  },
}
