import { StyleSheet } from 'react-native'

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F5F5',
  },
  header: {
    backgroundColor: '#007AFF',
    paddingVertical: 15,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerTitulo: {
    color: '#FFF',
    fontSize: 18,
    fontWeight: 'bold',
  },
  statusContainer: {
    backgroundColor: '#FFF',
    margin: 15,
    padding: 15,
    borderRadius: 8,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  statusTitulo: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 10,
    color: '#333',
  },
  statusTexto: {
    fontSize: 14,
    color: '#666',
    marginBottom: 5,
  },
  statusOnline: {
    color: '#4CAF50',
    fontWeight: 'bold',
  },
  statusOffline: {
    color: '#F44336',
    fontWeight: 'bold',
  },
  indicadorEtapas: {
    backgroundColor: '#FFF',
    marginHorizontal: 15,
    marginBottom: 15,
    padding: 15,
    borderRadius: 8,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  etapasContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  etapa: {
    alignItems: 'center',
    flex: 1,
  },
  etapaNumero: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#E0E0E0',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 5,
  },
  etapaNumeroAtiva: {
    backgroundColor: '#007AFF',
  },
  etapaNumeroCompleta: {
    backgroundColor: '#4CAF50',
  },
  etapaTextoNumero: {
    color: '#666',
    fontSize: 12,
    fontWeight: 'bold',
  },
  etapaTextoNumeroAtiva: {
    color: '#FFF',
  },
  etapaTitulo: {
    fontSize: 10,
    color: '#666',
    textAlign: 'center',
  },
  etapaTituloAtiva: {
    color: '#007AFF',
    fontWeight: 'bold',
  },
  etapaTituloCompleta: {
    color: '#4CAF50',
    fontWeight: 'bold',
  },
  linhaConetor: {
    height: 2,
    backgroundColor: '#E0E0E0',
    flex: 1,
    marginHorizontal: 10,
    marginTop: -15,
  },
  linhaConectorCompleta: {
    backgroundColor: '#4CAF50',
  },
  formulario: {
    flex: 1,
    backgroundColor: '#FFF',
    marginHorizontal: 15,
    marginBottom: 15,
    borderRadius: 8,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    padding: 15,
  },
  secaoTitulo: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 15,
    marginTop: 10,
  },
  campo: {
    marginBottom: 15,
  },
  label: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
    marginBottom: 5,
  },
  input: {
    borderWidth: 1,
    borderColor: '#DDD',
    borderRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    backgroundColor: '#FFF',
  },
  inputReadonly: {
    backgroundColor: '#F5F5F5',
    color: '#666',
  },
  textArea: {
    height: 80,
    textAlignVertical: 'top',
  },
  linhaHorizontal: {
    flexDirection: 'row',
    alignItems: 'flex-end',
  },
  ajuda: {
    fontSize: 12,
    color: '#666',
    marginTop: 5,
    fontStyle: 'italic',
  },
  seletorTipo: {
    flexDirection: 'row',
    marginBottom: 20,
    borderRadius: 6,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#DDD',
  },
  botaoTipo: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 15,
    backgroundColor: '#FFF',
    alignItems: 'center',
  },
  botaoTipoAtivo: {
    backgroundColor: '#007AFF',
  },
  textoTipo: {
    fontSize: 14,
    color: '#666',
    fontWeight: '600',
  },
  textoTipoAtivo: {
    color: '#FFF',
  },
  pickerContainer: {
    borderWidth: 1,
    borderColor: '#DDD',
    borderRadius: 6,
    backgroundColor: '#FFF',
  },
  picker: {
    height: 50,
  },
  botaoPreencherData: {
    backgroundColor: '#4CAF50',
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 6,
    alignItems: 'center',
    marginBottom: 15,
  },
  textoBotaoPreencherData: {
    color: '#FFF',
    fontSize: 14,
    fontWeight: '600',
  },
  itensHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  botaoAdicionarItem: {
    backgroundColor: '#4CAF50',
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 6,
  },
  textoBotaoAdicionarItem: {
    color: '#FFF',
    fontSize: 14,
    fontWeight: '600',
    marginLeft: 5,
  },
  semItens: {
    padding: 30,
    alignItems: 'center',
  },
  textoSemItens: {
    fontSize: 14,
    color: '#666',
    textAlign: 'center',
  },
  itemContainer: {
    borderWidth: 1,
    borderColor: '#DDD',
    borderRadius: 8,
    marginBottom: 15,
    backgroundColor: '#FAFAFA',
  },
  itemHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 15,
    backgroundColor: '#F0F0F0',
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
  },
  itemTitulo: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
    flex: 1,
  },
  itemAcoes: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  botaoEditar: {
    padding: 5,
    marginRight: 10,
  },
  botaoRemover: {
    padding: 5,
  },
  itemResumo: {
    padding: 15,
  },
  itemResumoTexto: {
    fontSize: 14,
    color: '#666',
  },
  itemDetalhes: {
    padding: 15,
    borderTopWidth: 1,
    borderTopColor: '#DDD',
  },
  totalGeral: {
    backgroundColor: '#E3F2FD',
    padding: 15,
    borderRadius: 8,
    marginTop: 15,
    alignItems: 'center',
  },
  textoTotalGeral: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1976D2',
  },
  botoesNavegacao: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 15,
    paddingVertical: 10,
    backgroundColor: '#FFF',
    borderTopWidth: 1,
    borderTopColor: '#DDD',
  },
  botaoNavegacao: {
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 6,
    minWidth: 100,
    alignItems: 'center',
  },
  botaoVoltar: {
    backgroundColor: '#6C757D',
  },
  botaoProximo: {
    backgroundColor: '#007AFF',
  },
  botaoEmitir: {
    backgroundColor: '#28A745',
  },
  botaoDesabilitado: {
    backgroundColor: '#CCC',
  },
  textoBotaoNavegacao: {
    color: '#FFF',
    fontSize: 14,
    fontWeight: '600',
  },
  textoBotaoDesabilitado: {
    color: '#999',
  },
  loading: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5F5F5',
  },
  loadingTexto: {
    marginTop: 10,
    fontSize: 16,
    color: '#666',
  },
  erro: {
    backgroundColor: '#FFEBEE',
    borderColor: '#F44336',
    borderWidth: 1,
    borderRadius: 6,
    padding: 15,
    marginBottom: 15,
  },
  erroTexto: {
    color: '#D32F2F',
    fontSize: 14,
  },
  sucesso: {
    backgroundColor: '#E8F5E8',
    borderColor: '#4CAF50',
    borderWidth: 1,
    borderRadius: 6,
    padding: 15,
    marginBottom: 15,
  },
  sucessoTexto: {
    color: '#2E7D32',
    fontSize: 14,
  },
  modal: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalConteudo: {
    backgroundColor: '#FFF',
    borderRadius: 8,
    padding: 20,
    margin: 20,
    maxWidth: 300,
    width: '100%',
  },
  modalTitulo: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 15,
    textAlign: 'center',
  },
  modalTexto: {
    fontSize: 14,
    color: '#666',
    marginBottom: 20,
    textAlign: 'center',
  },
  modalBotoes: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  modalBotao: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 6,
    minWidth: 80,
    alignItems: 'center',
  },
  modalBotaoPrimario: {
    backgroundColor: '#007AFF',
  },
  modalBotaoSecundario: {
    backgroundColor: '#6C757D',
  },
  modalTextoBotao: {
    color: '#FFF',
    fontSize: 14,
    fontWeight: '600',
  },
})