import { StyleSheet } from 'react-native'

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0c1c2c',
  },
  filtrosContainer: {
    backgroundColor: '#1a2332',
    padding: 20,
    marginHorizontal: 16,
    marginTop: 16,
    borderRadius: 12,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    borderWidth: 1,
    borderColor: '#1f6d7a',
  },

  dateContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  dateButton: {
    flex: 0.48,
    padding: 14,
    backgroundColor: '#243242',
    borderRadius: 8,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#1f6d7a',
  },
  dateButtonText: {
    color: '#1f6d7a',
    fontWeight: '600',
    fontSize: 13,
  },
  searchInput: {
    borderWidth: 1,
    borderColor: '#1f6d7a',
    borderRadius: 8,
    padding: 14,
    marginBottom: 16,
    color: '#1f6d7a',
    backgroundColor: '#243242',
    fontSize: 14,
  },
  filtrosRow: {
    marginBottom: 16,
  },
  filtroContainer: {
    flex: 1,
    marginRight: 16,
  },
  filtroLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#1f6d7a',
    marginBottom: 8,
  },
  statusButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  statusButton: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginHorizontal: 2,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#1f6d7a',
    backgroundColor: 'transparent',
    alignItems: 'center',
  },
  statusButtonActive: {
    backgroundColor: '#1f6d7a',
  },
  statusButtonText: {
    fontSize: 8,
    color: '#1f6d7a',
    fontWeight: '600',
    margin: 10,
  },
  statusButtonTextActive: {
    color: '#fff',
  },
  checkboxContainer: {
    flexDirection: 'column',
    marginBottom: 10,
    marginTop: 10,
    padding: 12,
    backgroundColor: '#243242',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#1f6d7a',
  },
  checkbox: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  checkboxText: {
    fontSize: 14,
    color: '#1f6d7a',
    fontWeight: '600',
    marginLeft: 8,
  },
  checkboxHelper: {
    fontSize: 12,
    color: '#4caf50',
    fontStyle: 'italic',
    marginLeft: 32,
  },
  actionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  buscarButton: {
    flex: 0.48,
    backgroundColor: '#1f6d7a',
    padding: 14,
    borderRadius: 8,
    alignItems: 'center',
    elevation: 2,
  },
  buscarButtonText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 14,
  },
  limparButton: {
    flex: 0.48,
    backgroundColor: '#ff6b6b',
    padding: 14,
    borderRadius: 8,
    alignItems: 'center',
    elevation: 2,
  },
  limparButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  // NOVO: Estilos para indicador de progresso
  progressContainer: {
    backgroundColor: '#1a2332',
    marginHorizontal: 16,
    marginTop: 8,
    padding: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#4caf50',
  },
  progressText: {
    color: '#4caf50',
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
    marginBottom: 8,
  },
  progressBar: {
    height: 8,
    backgroundColor: '#243242',
    borderRadius: 4,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: '#4caf50',
    borderRadius: 4,
  },
  listContainer: {
    padding: 16,
    paddingTop: 8,
    marginTop: 45,
  },
  itemContainer: {
    backgroundColor: '#1a2332',
    padding: 16,
    marginBottom: 5,
    marginHorizontal: 16,
    marginTop: 25,
    borderRadius: 10,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
    borderLeftWidth: 4,
    borderLeftColor: '#1f6d7a',
  },
  itemHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  clienteNome: {
    fontSize: 16,
    fontWeight: '600',
    flex: 1,
    color: '#f0f8ff',
  },
  valor: {
    fontSize: 16,
    fontWeight: '700',
    color: '#4caf50',
  },
  itemDetails: {
    marginBottom: 10,
  },
  detailText: {
    fontSize: 14,
    color: '#a0a0a0',
    marginBottom: 3,
  },
  itemFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  formaRecebimento: {
    fontSize: 12,
    color: '#1f6d7a',
    fontWeight: '500',
  },
  status: {
    fontSize: 11,
    fontWeight: '600',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
  },
  vencido: {
    backgroundColor: '#ffebee',
    color: '#f44336',
  },
  aVencer: {
    backgroundColor: '#e8f5e8',
    color: '#4caf50',
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 50,
  },
  emptyText: {
    textAlign: 'center',
    fontSize: 16,
    color: '#a0a0a0',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: '#303942',
    padding: 60,
    margin: 20,
    borderRadius: 12,
    padding: 20,
    maxHeight: '80%',
    width: '90%',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 20,
    textAlign: 'center',
    color: '#1f6d7a',
  },
  modalSection: {
    marginBottom: 12,
  },
  modalLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
    marginBottom: 4,
  },
  modalValue: {
    fontSize: 10,
    color: '#666',
  },
  modalActions: {
    marginTop: 20,
  },
  actionButton: {
    padding: 14,
    borderRadius: 8,
    alignItems: 'center',
    marginBottom: 10,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    flexDirection: 'row',
  },
  whatsappButton: {
    backgroundColor: '#25d366',
  },
  emailButton: {
    backgroundColor: '#1f6d7a',
  },
  cancelButton: {
    backgroundColor: '#757575',
  },
  actionButtonText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 14,
  },
  // NOVO: Estilo para texto secundário nos botões
  actionButtonSubtext: {
    color: '#fff',
    fontSize: 11,
    marginTop: 2,
    opacity: 0.8,
  },
  multiActionContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#1a2332',
    marginHorizontal: 16,
    marginBottom: 8,
    borderRadius: 8,
    elevation: 2,
    borderWidth: 1,
    borderColor: '#4caf50',
  },
  multiActionButton: {
    flex: 0.48,
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
    elevation: 2,
  },

  // Status buttons menores
  statusButtonSmall: {
    flex: 1,
    paddingVertical: 6,
    paddingHorizontal: 8,
    marginHorizontal: 2,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#ddd',
    backgroundColor: 'transparent',
    alignItems: 'center',
  },
  statusButtonSmallText: {
    fontSize: 11,
    color: '#666',
    fontWeight: '500',
  },

  batchActionsContainer: {
    position: 'absolute',
    bottom: 25,
    left: 20,
    right: 20,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#303942',
    borderRadius: 25,
    paddingVertical: 12,
    paddingHorizontal: 20,
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    borderWidth: 1,
    borderColor: '#e0e0e0',
    zIndex: 1000,
  },
  selectedCount: {
    fontSize: 12,
    fontWeight: '600',
    color: '#fff',
    marginRight: 15,
  },
  batchButtons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 15,
  },
  // Botão WhatsApp com ícone
  whatsButton: {
    backgroundColor: '#25d366',
    width: 45,
    height: 45,
    borderRadius: 22.5,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 4,
    shadowColor: '#25d366',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  whatsButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  // Botão Email com ícone
  emailButton: {
    backgroundColor: '#1976d2',
    width: 45,
    height: 45,
    borderRadius: 22.5,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 4,
    shadowColor: '#1976d2',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  emailButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  // Estilos para modal
  enviarButton: {
    backgroundColor: '#25d366',
    padding: 14,
    borderRadius: 8,
    alignItems: 'center',
    marginBottom: 10,
    elevation: 2,
  },
  enviarButtonText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 14,
  },
  fecharButton: {
    backgroundColor: '#757575',
    padding: 14,
    borderRadius: 8,
    alignItems: 'center',
    elevation: 2,
  },
  fecharButtonText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 14,
  },
})

export default styles
