import { StyleSheet } from 'react-native'

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#1a252f',
    padding: 16,
  },
  tabsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 16,
  },
  tabButton: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  tabButtonAtiva: {
    borderBottomColor: '#deb887',
  },
  tabText: {
    fontSize: 16,
    color: '#8a9ba8',
  },
  tabTextAtivo: {
    color: '#deb887',
    fontWeight: 'bold',
  },
  titulo: {
    fontSize: 24,
    fontWeight: 'bold',
    textAlign: 'center',
    marginTop: 16,
    marginBottom: 12,
    color: '#deb887',
  },
  incluirButton: {
    backgroundColor: '#303942',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    marginBottom: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#deb887',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  incluirButtonText: {
    color: '#deb887',
    fontWeight: 'bold',
    fontSize: 16,
  },
  searchContainer: {
    flexDirection: 'row',
    marginBottom: 16,
    gap: 8,
  },
  input: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#3d5a73',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    backgroundColor: '#2d4a5a',
    color: '#deb887',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  searchButton: {
    backgroundColor: '#303942',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#deb887',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  searchButtonText: {
    color: '#deb887',
    fontWeight: '600',
    fontSize: 14,
  },
  card: {
    backgroundColor: '#303942',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 6,
    borderLeftWidth: 4,
    borderLeftColor: '#deb887',
    borderWidth: 1,
    borderColor: '#3d5a73',
  },
  nome: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#deb887',
    marginBottom: 8,
  },
  numero: {
    fontSize: 14,
    color: '#deb887',
    fontWeight: '600',
    marginBottom: 4,
    opacity: 0.9,
  },
  codigo: {
    fontSize: 14,
    color: '#a8b8c8',
    marginBottom: 4,
  },
  unidade: {
    fontSize: 14,
    color: '#a8b8c8',
    marginBottom: 4,
  },
  saldo: {
    fontSize: 14,
    color: '#a8b8c8',
    marginBottom: 8,
  },
  actions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#3d5a73',
  },
  botao: {
    backgroundColor: '#303942',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#deb887',
    minWidth: 40,
    alignItems: 'center',
  },
  botaoTexto: {
    fontSize: 16,
    color: '#deb887',
  },
  footerText: {
    textAlign: 'center',
    color: '#a8b8c8',
    fontSize: 14,
    marginTop: 16,
    marginBottom: 20,
    fontStyle: 'italic',
  },
  label: {
    fontSize: 14,
    fontWeight: '600',
    marginTop: 12,
    marginBottom: 4,
    color: '#deb887',
  },
  botaoSalvar: {
    backgroundColor: '#303942',
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 12,
    margin: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#deb887',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
})
