import { StyleSheet } from 'react-native'

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0d0d0d',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  logo: {
    width: 120,
    height: 120,
    marginBottom: 10,
  },
  title: {
    fontFamily: 'FaunaOne_400Regular',
    fontSize: 28,
    color: '#faebd7',
    marginBottom: 20,
  },
  toggleContainer: {
    flexDirection: 'row',
    backgroundColor: '#1a1a1a',
    borderRadius: 8,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#333',
    overflow: 'hidden',
  },
  toggleButton: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 20,
    alignItems: 'center',
    backgroundColor: 'transparent',
  },
  toggleButtonActive: {
    backgroundColor: '#354972',
  },
  toggleText: {
    color: '#faebd7',
    fontSize: 14,
    fontWeight: '500',
  },
  toggleTextActive: {
    color: '#faebd7',
    fontWeight: 'bold',
  },
  inputContainer: {
    width: '100%',
    marginBottom: 15,
  },
  label: {
    color: '#faebd7',
    marginBottom: 5,
    marginLeft: 5,
    fontSize: 14,
  },
  inputBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1a1a1a',
    borderRadius: 8,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: '#333',
  },
  icon: {
    marginRight: 8,
  },
  input: {
    flex: 1,
    color: '#faebd7',
    height: 45,
  },
  button: {
    marginTop: 10,
    backgroundColor: '#1b263bff',
    paddingVertical: 12,
    paddingHorizontal: 30,
    borderRadius: 10,
    width: '100%',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 3,
  },
  buttonText: {
    color: '#faebd7',
    fontSize: 16,
    fontWeight: 'bold',
  },
  loaddingContainer: {
    marginTop: 15,
    alignItems: 'center',
    color: '#faebd7',
    backgroundColor: '#1b263bff',
    paddingVertical: 12,
    paddingHorizontal: 30,
    borderRadius: 10,
    width: '100%',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 3,
  },
  error: {
    marginTop: 15,
    color: '#f55',
    textAlign: 'center',
  },
  checkboxContainer: {
    marginBottom: 20,
    alignItems: 'center',
  },
  checkboxRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  checkbox: {
    width: 20,
    height: 20,
    borderWidth: 2,
    borderColor: '#faebd7',
    borderRadius: 4,
    marginRight: 10,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'transparent',
  },
  checkboxActive: {
    backgroundColor: '#007bff',
    borderColor: '#007bff',
  },
  checkboxLabel: {
    fontSize: 10,
    color: '#faebd7',
    fontFamily: 'FaunaOne_400Regular',
  },
  linkText: {
    color: '#faebd7',
    fontSize: 16,
    textDecorationLine: 'underline',
    marginTop: 5,
  },
  linkText2: {
    color: '#fff',
    fontSize: 16,
    alignItems: 'center',
    textAlign: 'center',
    marginTop: 5,
  },
})

export default styles
